workflows:
  ios-ipa-release:
    name: iOS IPA Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS Archive
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA from App
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r ../ipa/reps_app.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa